# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-24 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180907_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='shop_price',
            field=models.FloatField(default=0, verbose_name='本店价格'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='category_type',
            field=models.IntegerField(choices=[(3, '三级类目'), (1, '一级类目'), (2, '二级类目')], help_text='类目级别', verbose_name='类目级别'),
        ),
    ]
