# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-25 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180924_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='category_type',
            field=models.IntegerField(choices=[(3, '三级类目'), (2, '二级类目'), (1, '一级类目')], help_text='类目级别', verbose_name='类目级别'),
        ),
    ]
